<a href="https://colab.research.google.com/github/kacper-dobrow/tensorflow-course/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamental tensorflow concepts

More specifically:
*intro to tensors
*getting info on tensors
*manipulating tensors
*tensors and numPy
*tf.function()
*using GPUs with tf
*excercises

# Intro to tensors

In [1]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
#creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check no of dimns with .ndim
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check dimns of vector
vector.ndim

1

In [6]:
#create a matrix
matrix = tf.constant([[10,7],
                      [7,1]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  1]], dtype=int32)>

In [7]:
# check ndim of the matrix
matrix.ndim

2

In [8]:
#create a matrix with a specified datatype
another_matrix = tf.constant([[10.,7.],
                               [3.,2.],
                               [8.,9.]],dtype = tf.float16) #less space than the default 32bit
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
#no of dimns of another_matrix
another_matrix.ndim

2

In [11]:
# create a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>